Repository kauKoala/if-you-are-rich-then-do-not-solve-algorithm, pull requests merged in 2023-10, with the labels that each got.

#9 [231001] solve programmers 후보키
  dener8/programmers_후보키.py
Labels: 프로그래머스

#10 feat: solve codetree destory_turret
  suheoon/code_tree_destory_turret.cpp
Labels: 코드트리

#11 [231001] feat: solve 프로그래머스 - 연속된 부분 수열의 합
  hello70825/programmers_178870.py
Labels: 프로그래머스

#12 [231002] feat: solve 코드트리 - 싸움땅
  suheoon/code_tree_destory_turret.cpp
  suheoon/code_tree_fighting_ground.cpp
Labels: 코드트리

#13 [231002] feat: solve programmers 혼자 놀기의 달인
  dener8/programmers_혼자놀기의달인.py
Labels: 프로그래머스

#15 [231003] feat: solve programmers 광물캐기
  dener8/programmers_광물캐기.py
Labels: 프로그래머스

#16 [231003] feat: solve 프로그래머스 행렬 테두리 회전
  suheoon/programmers_rotate_matrix.cpp
Labels: 프로그래머스

#17 [231003] feat: solve 프로그래머스 - 혼자서 하는 틱택토
  hello70825/programmers_160585.py
Labels: 프로그래머스

#18 [231004] feat: solve programmers 소수찾기
  dener8/programmers_소수찾기.py
Labels: 프로그래머스

#19 [231004] feat: solve programmers_target_number
  suheoon/programmers_target_number.cpp
Labels: 프로그래머스

#20 [231004] feat: solve 프로그래머스 - 미로 탈출
  hello70825/programmers_159993.py
Labels: 프로그래머스

#22 [231005] feat: solve programmers 더맵게
  dener8/programmers_더맵게.py
Labels: 프로그래머스

#23 [231005] feat: solve programmers network
  suheoon/programmers_network.cpp
Labels: 프로그래머스

#24 [231006] feat: solve 프로그래머스 - 호텔 대실
  hello70825/programmers_155651.py
Labels: 프로그래머스

#25 [231006] feat: solve programmers 게임맵최단거리
  dener8/programmers_게임맵최단거리.py
Labels: 프로그래머스

#26 [231006] feat: solve programmers_travle_route
  suheoon/programmers_travel_route.cpp
Labels: 프로그래머스

#27 [231007] feat: solve pg distant node
  suheoon/pg_distant_node.cpp
Labels: 프로그래머스

#28 [231007] feat: solve programmers 기능개발
  dener8/programmers_기능개발.py
Labels: 프로그래머스

#29 [231007] feat: solve 프로그래머스 - 무인도 여행
  hello70825/programmers_154540.py
Labels: 프로그래머스

#31 [231008] feat: solve pg delivering
  suheoon/programmers_delivering.cpp
Labels: 프로그래머스

#32 [231008] feat: solve programmers 구명보트
  dener8/programmers_구명보트.py
Labels: 프로그래머스

#33 [231008] feat: solve 프로그래머스 - 숫자 변환하기
  hello70825/programmers_154538.py
Labels: 프로그래머스

#34 [231009] feat: solve programmers 게임맵최단거리
  suheoon/pg_1.cpp
Labels: 프로그래머스

#39 [231010] feat: solve 프로그래머스 - 시소 짝꿍
  hello70825/programmers_152996.py
Labels: 프로그래머스

#40 [231010] feat: solve 프로그래머스 - 폰켓몬
  d0ri123/Programmers02.java
Labels: 프로그래머스

#41 [231010] feat: solve programmers 표현 가능한 이진트리
  suheoon/pg_2.cpp
Labels: 프로그래머스

#42 [231010] feat: solve programmers 땅따먹기
  dener8/programmers_땅따먹기.py
Labels: 프로그래머스

#46 [231011] feat: solve programmers 피로도
  dener8/programmers_피로도.py
Labels: 프로그래머스

#47 [231012] feat: solve programmers 전화번호 목록
  d0ri123/Programmers05.java
Labels: 프로그래머스

#49 [231012] feat: BOJ 18808 스티커 붙이기
  jiwon83/BOJ_18808_스티커붙이기.java
Labels: 백준

#50 [231012] feat: solve programmers 타겟넘버
  dener8/programmers_타겟넘버.py
Labels: 프로그래머스

#51 [231012] feat: solve 프로그래머스 - 올바른 괄호
  hello70825/programmers_12909.py
Labels: 프로그래머스
