Repository kauKoala/if-you-are-rich-then-do-not-solve-algorithm, pull requests merged in 2023-09, with the labels that each got.

#1 feat: solve BOJ 16967
  suheoon/README.md
  suheoon/boj_16967.cpp
Labels: 백준

#2 feat: solve BOJ 18232
  hello70825/BOJ_18232.py
  hello70825/README.md
Labels: 백준

#3 feat: solve 프로그래머스 요격 시스템
  hello70825/PRGS_LV2_181188.py
  hello70825/programmers_181188.py
Labels: 프로그래머스

#6 [230930] BOJ - RPG Extreme, 프로그래머스 - 두 원 사이의 정수 쌍
  hello70825/BOJ_17081.py
  hello70825/PRGS_LV2_181188.py
  hello70825/programmers_181187.py
Labels: 백준, 프로그래머스

#7 [230930] programmers 호텔대실
  dener8/programmers_호텔대실.py
Labels: 프로그래머스

#8 feat: solve BOJ 13458
  suheoon/boj_13458.cpp
  suheoon/code_tree_maze_runner.cpp
Labels: 백준, 코드트리
